### 게시글 작성
POST http://localhost:8080/boards
Content-Type: application/json

{
  "title": "첫 글",
  "content": "게시판 테스트입니다.",
  "userId": 1
}

### 게시글 목록 조회
GET http://localhost:8080/boards

### 게시글 상세 조회
GET http://localhost:8080/boards/1

### 게시글 수정
PUT http://localhost:8080/boards/1
Content-Type: application/json

{
  "title": "수정된 제목",
  "content": "수정된 내용입니다."
}

### 게시글 삭제
DELETE http://localhost:8080/boards/1